### ISSUE TITLE
Can't install specific node version

### ISSUE THREAD

**Issue by louiszawadzki** [fansible/ansible-provisioning-tywin#30]
When I try to provision a node.js project I get this error : 

```
TASK: [nodejs | Install dependencies] *****************************************
ok: [10.0.0.10]

TASK: [nodejs | Add APT key] **************************************************
ok: [10.0.0.10]

TASK: [nodejs | Add APT repository] *******************************************
ok: [10.0.0.10] => (item=deb https://deb.nodesource.com/node_4.x trusty main)
ok: [10.0.0.10] => (item=deb-src https://deb.nodesource.com/node_4.x trusty main)

TASK: [nodejs | Install nodejs] ***********************************************
failed: [10.0.0.10] => {"failed": true}
stderr: E: Version '4.2.3*' for 'nodejs' was not found

stdout: Reading package lists...
Building dependency tree...
Reading state information...

msg: '/usr/bin/apt-get -y -o "Dpkg::Options::=--force-confdef" -o "Dpkg::Options::=--force-confold"   install 'nodejs=4.2.3*'' failed: E: Version '4.2.3*' for 'nodejs' was not found


FATAL: all hosts have already failed -- aborting
```

It seems that you can only install the latest node.js version using package managers on ubuntu trusty.

**Comment by louiszawadzki** [comment]
I can think of two ways of installing node : 
1. install the latest version : 
   That can be done if in `devops/provisioning/roles/nodejs/defaults/main.yml` you change line 4 `nodejs_version: 4.2.3` by `nodejs_version: 4`.
2. install a specific node version : 
   According to [this Stack Overflow post](http://stackoverflow.com/a/34540089) it can only be done by downloading the .deb file. Looking at [how to install .deb package](http://chaosmail.github.io/programming/2015/03/04/install-deb-packages-in-ansible/) I came up with the following for `devops/provisioning/roles/nodejs/tasks/install.deb.yml` : 

```
---

- name: Install dependencies
  apt: name=apt-transport-https

# Install the .deb 
- name: Check if nodejs is installed
  command: dpkg-query -W {{ nodejs_package_name }}
  register: nodejs_check_deb
  failed_when: nodejs_check_deb.rc > 1
  changed_when: nodejs_check_deb.rc == 1

- name: Download nodejs
  get_url:
    url=https://deb.nodesource.com/node_4.x/pool/main/n/nodejs/{{nodejs_package_name}}.deb
    dest="/home/vagrant/{{nodejs_package_name}}.deb"
  when: nodejs_check_deb.rc == 1

- name: Install nodejs
  apt: deb="/home/vagrant/{{nodejs_package_name}}.deb"
  sudo: true
  when: nodejs_check_deb.rc == 1

# Latest packages doesn't have 'node' executable anymore
# It were renamed to 'nodejs'. Add link to support old
# cookbooks which use the legacy 'node' command.
- stat: path=/usr/bin/node
  register: node_bin

- name: Add legacy node link
  file: src=/usr/bin/nodejs dest=/usr/bin/node state=link
  when: not node_bin.stat.exists
```

where `nodejs_package_name: "nodejs_{{nodejs_version}}-1nodesource1~{{ansible_distribution_release}}1_amd64"` is specified in `devops/provisioning/roles/nodejs/defaults/main.yml`.
